import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { FiEdit2, FiPlus, FiTrash2 } from 'react-icons/fi';
import { createAnnouncement, deleteAnnouncement, fullUrl, listAnnouncements, updateAnnouncement, uploadImage, uploadServiceVideo } from '../api';
import { Empty, Loading, Modal, btnDanger, btnPrimary, inputCls } from '../components/ui';

const blank = { title: '', content: '', image_url: '', video_url: '', published: true };
export default function Announcements() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank);
  const load = () => listAnnouncements().then(setItems).catch(() => toast.error('មិនអាចទាញព័ត៌មានបាន')).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const open = (item = null) => { setEditing(item); setForm(item ? { title: item.title, content: item.content, image_url: item.image_url || '', video_url: item.video_url || '', published: item.published } : blank); setModal(true); };
  const upload = async (kind, file) => { if (!file) return; try { const result = kind === 'image' ? await uploadImage(file) : await uploadServiceVideo(file); setForm({ ...form, [kind === 'image' ? 'image_url' : 'video_url']: result.url }); toast.success('បាន upload រួច'); } catch (_) { toast.error('Upload មិនបានសម្រេច'); } };
  const save = async (e) => { e.preventDefault(); try { if (editing) await updateAnnouncement(editing.id, form); else await createAnnouncement(form); toast.success('បានរក្សាទុកព័ត៌មានរួច'); setModal(false); load(); } catch (err) { toast.error(err?.response?.data?.detail || 'មិនអាចរក្សាទុកបាន'); } };
  const remove = async (item) => { if (!window.confirm(`លុប “${item.title}” មែនទេ?`)) return; try { await deleteAnnouncement(item.id); toast.success('បានលុប'); load(); } catch (_) { toast.error('មិនអាចលុបបាន'); } };
  if (loading) return <Loading />;
  return <div><div className="flex items-start justify-between gap-4 mb-6"><div><p className="text-xs font-bold tracking-widest text-pink-600">ROVISTAR ONLY</p><h1 className="text-2xl font-bold">ព័ត៌មានសំខាន់ៗ</h1><p className="text-sm text-gray-500 mt-1">បញ្ចូល និងបោះផ្សាយតែទៅ website `rovistar` មួយប៉ុណ្ណោះ។</p></div><button className={btnPrimary} onClick={() => open()}><FiPlus className="inline mr-1" />បន្ថែមព័ត៌មាន</button></div><div className="bg-white rounded-xl shadow-sm overflow-hidden">{items.length ? <div className="divide-y">{items.map((item) => <div className="p-4 flex items-center gap-4" key={item.id}>{item.image_url && <img src={fullUrl(item.image_url)} alt="" className="w-16 h-12 rounded object-cover" />}<div className="flex-1 min-w-0"><div className="font-semibold truncate">{item.title}</div><div className="text-xs text-gray-500 truncate">{item.content}</div><span className={`inline-block mt-1 text-xs font-semibold ${item.published ? 'text-green-600' : 'text-gray-400'}`}>{item.published ? 'ផ្សាយរួច' : 'Draft'}</span></div><button className="p-2 text-slate-600" onClick={() => open(item)}><FiEdit2 /></button><button className="p-2 text-red-500" onClick={() => remove(item)}><FiTrash2 /></button></div>)}</div> : <Empty message="មិនទាន់មានព័ត៌មានទេ" />}</div><Modal open={modal} title={editing ? 'កែព័ត៌មាន' : 'បន្ថែមព័ត៌មាន'} onClose={() => setModal(false)} wide><form onSubmit={save} className="space-y-4"><input className={inputCls} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="ចំណងជើង" required /><textarea className={inputCls} rows="6" value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} placeholder="សរសេរព័ត៌មាន..." required /><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">រូបភាព<input type="file" accept="image/*" className="block mt-1 text-xs" onChange={(e) => upload('image', e.target.files?.[0])} />{form.image_url && <img src={fullUrl(form.image_url)} alt="Preview" className="mt-2 h-24 rounded object-cover" />}</label><label className="text-sm">វីដេអូ<input type="file" accept="video/*" className="block mt-1 text-xs" onChange={(e) => upload('video', e.target.files?.[0])} />{form.video_url && <video src={fullUrl(form.video_url)} className="mt-2 h-24 rounded" controls />}</label></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.published} onChange={(e) => setForm({ ...form, published: e.target.checked })} />បោះផ្សាយភ្លាម</label><button className={btnPrimary}>រក្សាទុក</button></form></Modal></div>;
}
