import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { FiMessageCircle, FiSend } from 'react-icons/fi';
import { listSupportConversations, replySupportConversation } from '../api';

export default function SupportInbox() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [reply, setReply] = useState('');
  const refresh = async () => { const data = await listSupportConversations(); setItems(data); setSelected((current) => data.find((item) => item.id === current?.id) || data[0] || null); };
  useEffect(() => { refresh().catch(() => toast.error('មិនអាចទាញ chat បាន')); const timer = setInterval(() => refresh().catch(() => {}), 10000); return () => clearInterval(timer); }, []);
  const send = async (event) => { event.preventDefault(); if (!selected || !reply.trim()) return; try { await replySupportConversation(selected.id, { body: reply }); setReply(''); await refresh(); } catch { toast.error('មិនអាចផ្ញើសារបាន'); } };
  return <div className="max-w-6xl"><h2 className="text-2xl font-bold text-slate-900 mb-6">Customer Support Inbox</h2><div className="bg-white border rounded-2xl grid md:grid-cols-[300px_1fr] min-h-[560px] overflow-hidden"><aside className="border-r bg-slate-50">{items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className={`w-full text-left p-4 border-b ${selected?.id === item.id ? 'bg-white border-l-4 border-l-sky-500' : ''}`}><b className="block text-sm">{item.visitor_name || 'Visitor'}</b><span className="text-xs text-slate-500">{item.shop_name}</span><p className="text-xs mt-2 truncate">{item.messages.at(-1)?.body}</p></button>)}{!items.length && <p className="p-5 text-sm text-slate-500">No customer chats yet.</p>}</aside><section className="flex flex-col">{selected ? <><header className="p-5 border-b"><b>{selected.visitor_name || 'Visitor'}</b><span className="ml-2 text-sm text-slate-500">{selected.visitor_contact}</span></header><div className="flex-1 p-5 space-y-3 overflow-auto">{selected.messages.map((message) => <div key={message.id} className={`max-w-[80%] p-3 rounded-2xl text-sm ${message.sender === 'admin' ? 'ml-auto bg-slate-900 text-white' : 'bg-slate-100 text-slate-800'}`}>{message.body}</div>)}</div><form onSubmit={send} className="p-4 border-t flex gap-2"><input value={reply} onChange={(e) => setReply(e.target.value)} placeholder="Reply to customer..." className="flex-1 border rounded-xl px-4"/><button className="bg-sky-600 text-white p-3 rounded-xl"><FiSend /></button></form></> : <div className="m-auto text-center text-slate-400"><FiMessageCircle className="mx-auto text-4xl mb-3"/>Choose a conversation</div>}</section></div></div>;
}
